import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  guideSidebar: [
    {
      type: "autogenerated",
      dirName: ".", // 현재 docs 폴더의 구조를 기반으로 자동 생성
    },
  ],
};

export default sidebars;
