import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  // But you can create a sidebar manually
  guideSidebar: [
    {
      type: "category",
      label: "관리자용 포커스팡",
      items: [
        "admin-guide/feature",
        "admin-guide/login",
        "admin-guide/usage",
        "admin-guide/teacher-account-management",
        "admin-guide/admin-account-management",
        "admin-guide/student-account-management",
        "admin-guide/setting",
      ],
    },
    {
      type: "category",
      label: "선생님용 포커스팡",
      items: [
        "teacher-guide/login",
        "teacher-guide/add-class",
        "teacher-guide/delete-class",
        "teacher-guide/student-list",
        "teacher-guide/announcement",
        "teacher-guide/delete-announcement",
        "teacher-guide/dashboard",
        "teacher-guide/focustime",
        "teacher-guide/group-activity",
        "teacher-guide/assignment",
        "teacher-guide/quizpang",
        "teacher-guide/web-app-control",
        "teacher-guide/edit-info",
        "teacher-guide/logout",
      ],
    },
    {
      type: "category",
      label: "학생용 포커스팡",
      items: [
        "student-guide/android-install-guide",
        "student-guide/android-setup",
        "student-guide/window-install",
        "student-guide/window-setup",
        "student-guide/chromebook-install",
        "student-guide/login",
        "student-guide/add-class",
        "student-guide/display-in-class",
        "student-guide/web-app-control",
        "student-guide/announcement",
        "student-guide/assignment",
        "student-guide/group-activity",
        "student-guide/quizpang",
        "student-guide/logout",
      ],
    },
  ],
};

export default sidebars;
