import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// 기본 사이드바 정의
const sidebars: SidebarsConfig = {
  elementarySidebar: [
    {
      type: "doc",
      id: "elementary/intro",
      label: "초등학교 포커스팡 가이드",
      className: "sidebar-intro",
    },
    {
      type: "autogenerated",
      dirName: "elementary/categories",
    },
  ],
  middlehighSidebar: [
    {
      type: "doc",
      id: "middlehigh/intro",
      label: "중고등학교 포커스팡 가이드",
      className: "sidebar-intro",
    },
    {
      type: "autogenerated",
      dirName: "middlehigh/categories",
    },
  ],
};

export default sidebars;
